<?php

namespace Ringierimu\MultiTenancy\Tests;

use Ringierimu\MultiTenancy\MultiTenancyServiceProvider;

/**
 * Class TestCase
 * @package Ringierimu\MultiTenancy
 */
abstract class TestCase extends \Orchestra\Testbench\TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withFactories(__DIR__ . '/Fixtures/database/factories');
        $this->loadMigrationsFrom(__DIR__ . '/Fixtures/database/migrations');
        $this->loadLaravelMigrations();
    }

    protected function getPackageProviders($app)
    {
        return [MultiTenancyServiceProvider::class];
    }
}
